import type { Metadata } from "next";
import "./globals.css";
import {AppProvider} from "./appProvider.js";


export const metadata: Metadata = {
  title: "Predictoro",
  description: "Generated by create next app",
  
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <AppProvider>
    <html lang="en" >
      <body >
        {children}
      </body>
    </html>
    </AppProvider>
  );
}
